# Generated by Django 5.0.4 on 2024-10-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('about_tich', models.TextField()),
                ('phone', models.IntegerField(max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('professions', models.ManyToManyField(to='quiz.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_students', models.CharField(max_length=30)),
                ('phone_students', models.IntegerField(max_length=12)),
                ('lessoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='quiz.lesson')),
                ('ticher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.ticher')),
            ],
        ),
    ]
