# Generated by Django 5.0.4 on 2024-10-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_lesson_ticher_orderlesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlesson',
            old_name='lessoon',
            new_name='lesson',
        ),
    ]
