# Generated by Django 5.0.4 on 2024-11-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_orderlesson_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('about_course', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('extra_feildes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='quiz.categorycourse')),
            ],
        ),
    ]
