# Generated by Django 5.0.4 on 2024-11-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_categorycourse_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewKnowlege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('emodje', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
        ),
        migrations.AlterField(
            model_name='orderlesson',
            name='phone_students',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticher',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
