# Generated by Django 5.0.4 on 2024-11-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
